export const ROUTES = {
  home: "/",
  dashboard: "/dashboard",
  relatorios: "/relatorios",
  categorias: "/categorias",
  contas: "/contas",
  cartoes: "/cartoes",
  parcelamentos: "/parcelamentos",
  planejamentos: "/planejamentos",
  movimentacoes: "/movimentacoes",
  recorrencias: "/recorrencias",
  fluxoMensal: "/fluxo-mensal",
  metas: "/metas",
  dados: "/dados",
} as const
